### PR TITLE
config: fix wrong err check

### LINKED ISSUE #349: config: tests failing when called individually
- config version (080ab42):
- Operating system: linux ubuntu 19.04
- Go version: go version go1.12.2 linux/amd64
## Description
Hey guys, Im using the config package to load a `DATABASE_URL` to a env but while testing I noticed that It was not loading properly, so I dug into the code to find that many of the tests doesnt unset the env vars so the other tests doesnt fail because they are getting the other configs from unwanted environment variables.

This happens when you dont use the `prest.toml` file.
...
Some log: 
```shell
someapi git:(master) DATABASE_URL=postgres://xxxxx:password@zzzz.compute-1.amazonaws.com:5432/wwwww?sslmode=require go run main.go

2019/04/08 09:27:43 [warning] Debug ON
2019/04/08 09:27:43 [error] Queries directory  is not created2019/04/08 09:27:43 [msg] &{HTTPHost:0.0.0.0 HTTPPort:3000 PGHost:zzzz.compute-1.amazonaws.com PGPort:5432 PGUser: PGPass: PGDatabase: PGURL:postgres://xxxx:password@zzzz.compute-1.amazonaws.com:5432/wwwww?sslmode=require ContextPath: SSLMode:disable SSLCert: SSLKey: SSLRootCert: PGMaxIdleConn:0 PGMAxOpenConn:0 PGConnTimeout:0 JWTKey:lllll JWTAlgo: MigrationsPath:./migrations QueriesPath:./queries AccessConf:{Restrict:false Tables:[]} CORSAllowOrigin:[] CORSAllowHeaders:[] Debug:true Adapter:<nil> EnableDefaultJWT:false EnableCache:true HTTPSMode:false HTTPSCert: HTTPSKey:}


2019/04/08 09:27:43 [error] pq: no pg_hba.conf entry for host "186.228.131.90", user "dbname=", database "dbname=", SSL off
exit status 255
```

### Tests
If you run only the specific test for the database_url on the config package you'll get the following error:
```shell
➜  config git:(master) ✗ go test -run TestDatabaseURL$
--- FAIL: TestDatabaseURL (0.00s)
    config_test.go:155: expected database name: mydatabase, got: 
    config_test.go:161: expected database port: 1234, got: 5432
    config_test.go:164: expected database user: user, got: 
    config_test.go:167: expected database password: pass, got: 
    config_test.go:185: expected database user: user, got: 
    config_test.go:188: expected database password: password, got: 
FAIL
exit status 1
FAIL    github.com/prest/config 0.004s
```

I'll do more testing and provide a PR if necessary  to fix it.

### PR DESCRIPTION
**Pull request by arxdsilva**
fix prest/prest#349

It is already solved on #26, invalidade this if It's already merged

### CODE REVIEW

**Review by joelmdesouza — APPROVED** [review]
LGTM

**Review by crgimenes — APPROVED** [review]
LGTM

**Review by felipeweb — COMMENTED** [review]
conflicts need to be resolved

**Comment by felipeweb** [comment]
closing in favor #26

**Pull request closed without merging**
