### PR TITLE
https

### PR DESCRIPTION
**Pull request by RekGRpth**

### CODE REVIEW

**Review by felipeweb — APPROVED** [review]

**Review by tiaguinho — COMMENTED** [review]
I don't think that ```https.cert``` and ```https.key```need default values, since when ```https.mode```is false these two configurations aren't used.

make sense @crgimenes @felipeweb @avelino

**Comment by RekGRpth** [comment]
I did this to don't specify they if https.mode is true

**Review by crgimenes — APPROVED** [review]
LGTM

**Comment by felipeweb** [comment]
Thank you @RekGRpth

**Pull request merged**
